-- Gradebook column groups as persisted rows.
--
-- Until now a column's group was inferred in the browser from its slug prefix and
-- sort_order contiguity. This adds a table for groups and a nullable reference
-- from gradebook_columns to it. Existing columns stay ungrouped (NULL) until they
-- are backfilled. Group names are not unique: two separate groups in one gradebook
-- may share a display label.
--
-- The FK column is gradebook_column_group_id rather than group_id because group_id
-- already means an assignment group in the gradebook recalculation functions.

CREATE TABLE "public"."gradebook_column_groups" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "class_id" bigint NOT NULL REFERENCES "public"."classes"("id"),
    "gradebook_id" bigint NOT NULL REFERENCES "public"."gradebooks"("id"),
    "name" text NOT NULL
);

ALTER TABLE "public"."gradebook_columns"
    ADD COLUMN "gradebook_column_group_id" bigint
    REFERENCES "public"."gradebook_column_groups"("id");
